[package]
name = "sensor_mqtt"
version = "0.2.0"
authors = ["Andrew Rowson <github@growse.com>"]
edition = "2021"

[dependencies]
bme280 = { version = "0.2.1", features = ["serde"] }
linux-embedded-hal = "0.3.2"
log = "0.4"
rumqttc = "0.10"
env_logger = "0.9"
i2cdev = "0.5"
config = "0.11"
clap = { version = "3.0.13", features = ["derive"] }
serde_derive = "1"
serde = { version = "1.0", features = ["derive"] }
whoami = "1"
serde_json = "1"