[package]
name = "sensor_mqtt"
version = "0.2.0"
authors = ["Andrew Rowson <github@growse.com>"]
edition = "2018"

[dependencies]

bme280 = "0.2.1"
linux-embedded-hal = "0.3.0"
mqtt-protocol = "0.8.1"
log = "0.4.11"
env_logger = "0.7.1"
i2cdev = "0.4.4"
confy = "0.4.0"
serde_derive = "1.0.115"
serde = { version = "1.0", features = ["derive"] }