[package]
name = "sensor_mqtt"
version = "0.2.0"
authors = ["Andrew Rowson <github@growse.com>"]
edition = "2018"

[dependencies]

bme280 = { version = "0.2.1", features = ["serde"] }
linux-embedded-hal = "0.3.0"

log = "0.4.13"
rumqttc = "0.4.0"
env_logger = "0.8.2"
i2cdev = "0.4.4"
config = "0.10.1"
clap = "3.0.0-beta.2"
serde_derive = "1.0.115"
serde = { version = "1.0", features = ["derive"] }
whoami = "1.1.0"
serde_json = "1.0.61"